name = "Pack Pokebouli"
author = "Mazabouli"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec93ccc095c2f2ea9335c7bfd51c62a148437cd53eb1a1c7691859b29e235a31"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
