name = "Pack Pokebouli"
author = "Mazabouli"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d64dc028fb1256499d810a0e48bfdce122d89d6df9dfebab273f0162add3bf3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
